"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Wiki-to-Speech.py']
DATA_FILES = [('.',['LICENSE.txt','script.txt']),
               ('static/demo',['static/demo/img0.jpg','static/demo/img1.jpg'])]
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
